### Signature Assignment

Learning Goals

By completing this assignment, you will:

* Load data from a CSV file
* Convert data into NumPy arrays
* Access and process rows individually
* Perform basic numerical operations

### Step 1: Load file
You are given a CSV file named: scores.csv

### Step 2: Pre-Process Data
* Import NumPy.
* Load the numeric data from the CSV file into a NumPy array.
* Ignore the header row.
* Ignore the first column (names).

### Step 3: Process Each Row

For each student (each row in the array):

* Convert the row into a NumPy array.

    Calculate:

        - Total score

        - Average score

Print the results in this format:

Student 1 - Total: __ , Average: __

### Step 4: Conditional Processing

For each student:

    * If the average is ≥ 85, print "Excellent"
    * If the average is between 70 and 84, print "Good"
    * Otherwise, print "Needs Improvement"

In [2]:
%pip install numpy

   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.4 MB ? eta -:--:--
    --------------------------------------- 0.3/12.4 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.4 MB 1.5 MB/s eta 0:00:09
   ---- ----------------------------------- 1.3/12.4 MB 2.0 MB/s eta 0:00:06
   ----- ---------------------------------- 1.8/12.4 MB 2.4 MB/s eta 0:00:05
   -------- ------------------------------- 2.6/12.4 MB 2.6 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/12.4 MB 2.5 MB/s eta 0:00:04
   ----------- ---------------------------- 3.7/12.4 MB 2.6 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.4 MB 2.7 MB/s eta 0:00:03
   ---------------- ----------------------- 5.0/12.4 MB 2.7 MB/s eta 0:00:03
   ----------------- ---------------------- 5.5/12.4 MB 2.7 MB/s eta 0:00:03
   ------------------- -------------------- 6.0/12.4 MB 2.6 MB/s eta 0:00:03
   -----------------

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
#Step 1 & 2
import numpy as np

scores = np.loadtxt("scores.csv", delimiter=",", skiprows=1, usecols=range(1, 4))
print(scores)


#Step 3
for i in range(len(scores)):
    row = scores[i]
    total = np.sum(row)
    average = np.mean(row)
    print(f"Student {i + 1}: Total = {total}, Average = {average}")


#Step 4
if average >= 85:
    print("Excellent")
elif average >= 70 and average < 85:
    print("Good")
else:
    print("Needs Improvement")




[[80. 85. 90.]
 [70. 75. 72.]
 [88. 92. 85.]
 [92. 89. 94.]
 [65. 68. 70.]]
Student 1: Total = 255.0, Average = 85.0
Student 2: Total = 217.0, Average = 72.33333333333333
Student 3: Total = 265.0, Average = 88.33333333333333
Student 4: Total = 275.0, Average = 91.66666666666667
Student 5: Total = 203.0, Average = 67.66666666666667
Needs Improvement


Reflection: To what extent and how did your work on this assignment help you learn
this learning outcome:

Answer: 

